#!/bin/bash

IFS=$'\n'
TAG=$1
shift

for host in $(ec2-ls $TAG); do
	echo -e "\n$(echo $host | awk '{print $1}'):\n" >&2
	ssh -o StrictHostKeyChecking=no -i ~/.ssh/$(echo $host | awk '{print $4}').pem root@$(echo $host | awk '{print $1}') "$@"
done

