#!/bin/sh

aws ec2 describe-instances --filters "Name=tag:Name,Values=$1" --query "Reservations[*].Instances[*].[PublicIpAddress,InstanceId,LaunchTime,KeyName,Tags[?Key=='Name'].Value|[0]]" --output=text | sort -k4,4 -k3,3 | column -t
